eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8086
spring:
  application:
    name: service-feign111
  main:
    allow-bean-definition-overriding: true
ribbon:
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: true
